name: deploy-website
on:
  push:
    branches:
      - main
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: yarn
        run: yarn
      - name: Run Prettier
        run: yarn prettier:check
      - name: Gatsby Build
        run: yarn build
      - name: zip build result
        run: tar -czvf public.tar.gz public
      - name: archive zip
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public.tar.gz
  deploy:
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: extract public
        run: tar -xzvf public.tar.gz
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
